"""Write the protocol-v2 confirmatory configs for the studies that passed the signal gate (PROTOCOL_V2 §1–3).

    python scripts/make_v2_main.py --sig1 RUN --sig2 RUN [--sigE RUN --cal-bal CAL] --cal CAL [--only A_R,C,...]

Studies enter only if their signal-pilot ``go`` is true (and, with --only, if listed: the PI's
confirmation). A–D share one stage on the ``v2_main`` split with N = the largest N among the
included studies; D adds a 60-episode content-counterfactual diagnostic on the same split; E runs
on ``v2_bal`` with balanced materials. Families are Holm-adjusted within each study.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
QIDS = ["NOW", "NOW_R", "START", "START_R", "WORD", "WORD_R", "ACC_RULE", "ACC_WORD", "CAP0", "CAP1", "U_CLOSED"]
DIAG_EPISODES = 60


def _signal(run_dir: Path) -> dict:
    doc = json.loads((run_dir / "signal.json").read_text())
    if not doc.get("consumable"):
        raise SystemExit(f"{run_dir.name}: signal output not consumable")
    return doc["studies"]


def _arm_spec(name: str) -> dict:
    """Arm name -> ArmConfig kwargs (names come from ArmConfig.name, so parsing is exact)."""
    parts = name.split("/")
    cond, mode = parts[0], parts[-1]
    spec: dict = {"condition": cond}
    if mode != "FULL":
        spec["readout_mode"] = mode
    if len(parts) == 2:
        return {**spec, **({"layer": 24} if cond == "C0" else {})}
    if parts[1].startswith("KV-"):
        return {**spec, "interface": "kv", "kv_scope": parts[1][3:], "gain": float(parts[2][1:])}
    return {**spec, "layer": int(parts[1][1:]), "form": parts[2], "gain": float(parts[3][1:])}


def build(args) -> dict[str, dict]:
    studies = {**_signal(args.sig1), **_signal(args.sig2)}
    if args.sigE:
        studies.update(_signal(args.sigE))
    only = set(args.only.split(",")) if args.only else None
    chosen = {k: v for k, v in studies.items() if v["go"] and (only is None or k in only)}
    if not chosen:
        raise SystemExit("no study passed the signal gate")
    configs: dict[str, dict] = {}
    main = {k: v for k, v in chosen.items() if k != "E"}
    if main:
        families = {k: [[c["arm1"], c["arm2"], c["metric"]] for c in v["comparisons"]] for k, v in main.items()}
        arms = ["C0/FULL"] + sorted({a for fam in families.values() for c in fam for a in c[:2]} - {"C0/FULL"})
        n = max(v["N"] for v in main.values())
        configs["v2_main"] = {
            "stage": "v2_main", "tag": "confirm", "split": "v2_main", "n_episodes": n, "seed": 0,
            "arms": [_arm_spec(a) for a in arms], "qids": QIDS, "episodes_per_batch": 40, "max_rows": 256,
            "calibration": {24: args.cal}, "post": ["contrasts"],
            "params": {"families": families, "signal_go": {k: v["N"] for k, v in main.items()}}}
        if "D" in main:
            kstar = next(c["arm1"] for c in main["D"]["comparisons"])
            configs["v2_main_diag"] = {
                "stage": "v2_main_diag", "tag": "confirm", "split": "v2_main", "n_episodes": DIAG_EPISODES, "seed": 0,
                "arms": [_arm_spec("C0/FULL"), _arm_spec(kstar), _arm_spec(kstar.replace("ONE/", "CF/", 1))],
                "qids": ["ACC_RULE", "ACC_WORD", "CAP0", "CAP1"], "all_rotations_first": DIAG_EPISODES,
                "episodes_per_batch": 40, "max_rows": 256, "calibration": {24: args.cal}, "post": ["pilot_c"]}
    if "E" in chosen:
        e = chosen["E"]
        fam = [[c["arm1"], c["arm2"], c["metric"]] for c in e["comparisons"]]
        arms = ["C0/FULL"] + sorted({a for c in fam for a in c[:2]} - {"C0/FULL"}) + ["LANG_UNTAG/FULL"]
        configs["v2_bal"] = {
            "stage": "v2_bal", "tag": "confirm", "split": "v2_bal", "n_episodes": e["N"], "seed": 0,
            "arms": [_arm_spec(a) for a in dict.fromkeys(arms)], "qids": QIDS, "episodes_per_batch": 40,
            "max_rows": 256, "calibration": {24: args.cal_bal}, "materials": args.materials, "post": ["contrasts"],
            "params": {"families": {"E": fam}}}
    return configs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sig1", type=Path, required=True)
    ap.add_argument("--sig2", type=Path, required=True)
    ap.add_argument("--sigE", type=Path)
    ap.add_argument("--cal", required=True)
    ap.add_argument("--cal-bal")
    ap.add_argument("--materials", default="balanced2")
    ap.add_argument("--only", help="comma-separated study names confirmed by the PI")
    args = ap.parse_args()
    for name, cfg in build(args).items():
        out = ROOT / "configs" / "v2" / f"{name}.yaml"
        out.write_text(f"# Protocol v2 confirmatory stage `{name}`. GENERATED by scripts/make_v2_main.py; do not edit.\n"
                       + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=None, width=140))
        print(f"wrote {out}: {len(cfg['arms'])} arms x {cfg['n_episodes']} episodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
