"""Write the protocol-v3 A′ signal-pilot config from the S-A′ matching output (PROTOCOL_V3 §3).

    python scripts/make_v3_aprime_signal.py S_STATIC_A_RUN [--out configs/v3/sig_aprime.yaml]

S_STATIC_A_RUN is a local copy of the S-A′ run. The STATIC gain comes from its static_match.json and
the layer-24 calibration path from its config.yaml, so the pilot writes the same direction that was
matched. The first comparison (KV-P w1 − matched STATIC on M, no direction) decides go/no-go.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
TARGET = "ONE/KV-P/w1/FULL"
QIDS = ["NOW", "NOW_R", "START", "START_R", "WORD", "WORD_R", "ACC_RULE", "ACC_WORD", "CAP0", "CAP1", "U_CLOSED"]


def match(run_dir: Path) -> tuple[dict, dict]:
    doc = json.loads((run_dir / "static_match.json").read_text())
    if not doc.get("consumable"):
        raise SystemExit(f"{run_dir.name}: static match is not consumable (smoke or incomplete)")
    m = doc["matches"].get(TARGET)
    if not m:
        raise SystemExit(f"{run_dir.name}: no STATIC match for {TARGET}")
    cal = yaml.safe_load((run_dir / "config.yaml").read_text())["calibration"]
    return m, cal


def build(m: dict, cal: dict) -> dict:
    arms = [{"condition": "C0", "layer": 24}, {"condition": "ONE", "interface": "kv", "kv_scope": "P", "gain": 1.0},
            {"condition": "STATIC", "layer": 24, "gain": float(m["gain"])}]
    return {"stage": "v3_sig_aprime", "tag": "signal", "split": "v3_sig_aprime", "n_episodes": 80, "seed": 0,
            "arms": arms, "qids": QIDS, "episodes_per_batch": 40, "max_rows": 256, "calibration": cal,
            "post": ["signal"], "params": {"studies": {"A'": [[TARGET, m["static_arm"], "M", "0"]]}, "min_effect": 0.3}}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("s_static_a", type=Path)
    ap.add_argument("--out", type=Path, default=ROOT / "configs" / "v3" / "sig_aprime.yaml")
    args = ap.parse_args()
    m, cal = match(args.s_static_a)
    note = (f"# STATIC matched to {TARGET} in {args.s_static_a.name}: gain {m['gain']}, ACC {m['static_acc']:.2f} "
            f"vs {m['target_acc']:.2f}, matched={m['matched']}")
    args.out.write_text("# Protocol v3 A' signal pilot, generated by scripts/make_v3_aprime_signal.py.\n" + note + "\n"
                        + yaml.safe_dump(build(m, cal), sort_keys=False))
    print(args.out.read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
