"""Write configs/pilot_c.yaml from the frozen Pilot A and Pilot B selections (protocol §10).

    python scripts/make_pilot_c.py PILOT_A_RUN_DIR PILOT_B_RUN_DIR [--out configs/pilot_c.yaml]

Pilot C: 30 new episodes; C0, ONE/TWO at g*, STATIC at g_s* (if executable), CF at g* (G2), and
extension A's ONE/TWO at each layer's g*_l from Pilot A. Only ACC/CAP/format readouts are run:
Pilot C re-checks frozen candidates and never re-selects.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

HEADER = """# Pilot C (protocol v0.5.2 §10). GENERATED by scripts/make_pilot_c.py; do not edit by hand.
# Pilot A run: {a}  (per-layer g*_l: {per_layer})
# Pilot B run: {b}  (form={form} layer={layer} g*={g} g_s*={gs} matched={matched})
"""


def _consumable(path: Path) -> dict:
    sel = json.loads(path.read_text())
    s = sel.get("selection")
    if not sel.get("consumable") or not isinstance(s, dict) or not s.get("ok"):
        raise SystemExit(f"{path}: not a consumable, successful selection")
    return sel


def build(pilot_a: Path, pilot_b: Path) -> tuple[dict, str]:
    sel_a = _consumable(pilot_a / "pilot_a_selection.json")
    sel_b = _consumable(pilot_b / "pilot_b_selection.json")
    a, b = sel_a["selection"], sel_b["selection"]
    form, layer = sel_b["form"], int(sel_b["layer"])
    if (form, layer) != (a["form"], int(a["layer"])):
        raise SystemExit("Pilot B ran at a different form/layer than Pilot A selected")
    cal = json.loads((pilot_a / "identity.json").read_text())["calibration"]
    g = float(b["g_star"])
    arms = [{"condition": "C0", "layer": layer},
            {"condition": "ONE", "form": form, "layer": layer, "gain": g},
            {"condition": "TWO", "form": form, "layer": layer, "gain": g}]
    if b["static_executable"] and b["g_static"] is not None:
        arms.append({"condition": "STATIC", "form": form, "layer": layer, "gain": float(b["g_static"])})
    arms.append({"condition": "CF", "form": form, "layer": layer, "gain": g})
    for lay, g_l in sorted(a["per_layer_gain"].items(), key=lambda kv: int(kv[0])):
        if g_l is None:
            continue  # layer marked unusable in Pilot A; not re-selected
        for cond in ("ONE", "TWO"):
            arm = {"condition": cond, "form": form, "layer": int(lay), "gain": float(g_l)}
            if arm not in arms:
                arms.append(arm)
    layers = sorted({arm["layer"] for arm in arms if arm["condition"] != "C0"})
    cfg = {
        "stage": "pilot_c", "tag": "recheck", "split": "pilot_c", "n_episodes": 30, "seed": 0,
        "arms": arms, "qids": ["ACC_RULE", "ACC_WORD", "CAP0", "CAP1"],
        "episodes_per_batch": 30, "max_rows": 256,
        "calibration": {lay: cal[str(lay)]["path"] for lay in layers},
        "post": ["pilot_c"],
    }
    header = HEADER.format(a=pilot_a.name, b=pilot_b.name, per_layer=a["per_layer_gain"], form=form, layer=layer,
                           g=g, gs=b["g_static"], matched=b["static_matched"])
    return cfg, header


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("pilot_a_run", type=Path)
    ap.add_argument("pilot_b_run", type=Path)
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "configs" / "pilot_c.yaml")
    args = ap.parse_args()
    cfg, header = build(args.pilot_a_run, args.pilot_b_run)
    args.out.write_text(header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=None, width=120))
    print(f"wrote {args.out} ({len(cfg['arms'])} arms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
