"""Write the protocol-v3 confirmatory config (PROTOCOL_V3 §7; PI decision 2026-09-25).

    python scripts/make_v3_confirm.py S_STATIC_A_RUN [--out configs/v3/v3_confirm.yaml]

S_STATIC_A_RUN is a local copy of the S-A′ run: the matched STATIC gain and its layer-24 calibration
come from there. Every other arm is fixed by §7: KV-P w1; K* (KV-P w2) answered with the link (FULL)
and with it cut (RF); the strict third-person frame at w2 and at w1.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from mb.conditions import ArmConfig

ROOT = Path(__file__).resolve().parents[1]
QIDS = ["NOW", "NOW_R", "START", "START_R", "WORD", "WORD_R", "ACC_RULE", "ACC_WORD", "CAP0", "CAP1", "U_CLOSED"]
N_CONFIRM = 600
TARGET = "ONE/KV-P/w1/FULL"


def static_match(run_dir: Path) -> tuple[dict, dict]:
    doc = json.loads((run_dir / "static_match.json").read_text())
    if not doc.get("consumable"):
        raise SystemExit(f"{run_dir.name}: static match is not consumable (smoke or incomplete)")
    m = doc["matches"].get(TARGET)
    if not m:
        raise SystemExit(f"{run_dir.name}: no STATIC match for {TARGET}")
    return m, yaml.safe_load((run_dir / "config.yaml").read_text())["calibration"]


def build(m: dict, cal: dict) -> dict:
    kv = {"condition": "ONE", "interface": "kv", "kv_scope": "P"}
    arms = [{"condition": "C0", "layer": 24}, {**kv, "gain": 1.0}, {"condition": "STATIC", "layer": 24, "gain": float(m["gain"])},
            {**kv, "gain": 2.0}, {**kv, "gain": 2.0, "readout_mode": "RF"},
            {**kv, "gain": 2.0, "partner_frame": "third_strict"}, {**kv, "gain": 1.0, "partner_frame": "third_strict"}]
    n = [ArmConfig(**a).name for a in arms]
    c0, w1, static, k, k_rf, k_3ps, w1_3ps = n
    families = {"A'": [[w1, static, "M"]],
                "RF": [[k, k_rf, "M"], [k_rf, c0, "M_NOW"]],
                "T3_w1": [[w1_3ps, w1, "M"]]}
    equivalence = {"T3_K*": {"arm1": k_3ps, "arm2": k, "effect_arm": k, "base": c0, "metric": "M", "margin": 0.2}}
    return {"stage": "v3_confirm", "tag": "confirm", "split": "v3_confirm", "n_episodes": N_CONFIRM, "seed": 0,
            "arms": arms, "qids": QIDS, "episodes_per_batch": 40, "max_rows": 256, "calibration": cal,
            "post": ["contrasts"], "params": {"families": families, "equivalence": equivalence}}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("s_static_a", type=Path)
    ap.add_argument("--out", type=Path, default=ROOT / "configs" / "v3" / "v3_confirm.yaml")
    args = ap.parse_args()
    m, cal = static_match(args.s_static_a)
    header = ("# Protocol v3 confirmatory stage `v3_confirm`. GENERATED by scripts/make_v3_confirm.py; do not edit.\n"
              f"# STATIC matched to {TARGET} in {args.s_static_a.name}: gain {m['gain']} (ACC {m['static_acc']:.2f} vs "
              f"{m['target_acc']:.2f}).\n")
    args.out.write_text(header + yaml.safe_dump(build(m, cal), sort_keys=False))
    print(args.out.read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
