"""Write the formal-stage configs from the frozen pilot artifacts (protocol v0.5.2 §7, §9, §10).

    python scripts/make_main.py PILOT_A_RUN PILOT_B_RUN PILOT_C_RUN [--out-dir configs]

Refuses unless all three pilots are consumable, the Pilot B selection succeeded, N was computed,
and G2 passed in Pilot C. Writes four configs, all on the ``main`` split (episode generation is
prefix-stable, so the first 60 / N_ext episodes are the same episodes in every stage):

- ``main.yaml``: N episodes, the full §7 condition set, first 60 episodes with all 4 rotations;
  post step ``confirmatory`` (the pre-registered §9 analysis).
- ``main_diag.yaml``: diagnostic subset (first 60 episodes, 4 rotations): C0, ONE(g*), CF(g*).
- ``ext_layers.yaml``: extension A on the first N_ext = min(N, 300) episodes.
- ``ext_masks.yaml``: extension B (nested masks k = 16/128/1024) on the first N_ext episodes.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

MASK_KS = (16, 128, 1024)
DIAG_EPISODES = 60
N_EXT_MAX = 300
HEADER = """# Formal stage `{stage}` (protocol v0.5.2, frozen as protocol-v1). GENERATED by scripts/make_main.py.
# Do not edit by hand. Sources: Pilot A {a}, Pilot B {b}, Pilot C {c}.
"""


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def frozen_parameters(pilot_a: Path, pilot_b: Path, pilot_c: Path) -> dict:
    sel_a, sel_b = _load(pilot_a / "pilot_a_selection.json"), _load(pilot_b / "pilot_b_selection.json")
    size, pc = _load(pilot_b / "sample_size.json"), _load(pilot_c / "pilot_c.json")
    for name, doc in (("Pilot A", sel_a), ("Pilot B", sel_b), ("sample size", size), ("Pilot C", pc)):
        if not doc.get("consumable"):
            raise SystemExit(f"{name} output is not consumable (smoke or incomplete)")
    a, b = sel_a["selection"], sel_b["selection"]
    if not (isinstance(a, dict) and a.get("ok") and isinstance(b, dict) and b.get("ok")):
        raise SystemExit("Pilot A or Pilot B selection failed; the formal stage is not executable")
    if size.get("N") is None:
        raise SystemExit("N was not computed")
    if pc.get("G2") != "pass":
        raise SystemExit(f"G2 = {pc.get('G2')}: per protocol §10 the formal stage does not run")
    n = int(size["N"])
    return {
        "protocol": "v1", "form": sel_b["form"], "layer": int(sel_b["layer"]),
        "g_star": float(b["g_star"]), "main_gains": [float(g) for g in b["main_gains"]],
        "g_static": None if b["g_static"] is None else float(b["g_static"]),
        "static_matched": bool(b["static_matched"]), "static_executable": bool(b["static_executable"]),
        "static_neighbors": [float(g) for g in b["static_neighbors"]],
        "per_layer_gain": {str(k): (None if v is None else float(v)) for k, v in a["per_layer_gain"].items()},
        "N": n, "N_ext": min(n, N_EXT_MAX), "diag_episodes": DIAG_EPISODES,
        "sources": {"pilot_a": pilot_a.name, "pilot_b": pilot_b.name, "pilot_c": pilot_c.name},
        "g2": pc["g2_detail"], "sample_size": {"sd_of_paired_M": size["sd_of_paired_M"], "mde_at_N": size["mde_at_N"]},
    }


def build_all(pilot_a: Path, pilot_b: Path, pilot_c: Path) -> dict[str, dict]:
    fz = frozen_parameters(pilot_a, pilot_b, pilot_c)
    form, layer, g = fz["form"], fz["layer"], fz["g_star"]
    calibration = _load(pilot_a / "identity.json")["calibration"]

    def bridged(cond: str, gain: float, lay: int = layer, **kw) -> dict:
        return {"condition": cond, "form": form, "layer": lay, "gain": gain, **kw}

    main = [{"condition": "C0", "layer": layer, "recipients": ["A", "B"]}]
    main += [bridged("ONE", x) for x in fz["main_gains"]]
    main += [bridged("TWO", x, recipients=["A", "B"]) for x in fz["main_gains"]]
    if fz["static_executable"] and fz["g_static"] is not None:
        main += [bridged("STATIC", x) for x in sorted({fz["g_static"], *fz["static_neighbors"]})]
    main += [{"condition": "LANG_TAG", "layer": layer}, {"condition": "LANG_UNTAG", "layer": layer}]
    main += [bridged("MISMATCH", g), bridged("SCRAM", g)]
    main += [bridged(cond, g, readout_mode=mode) for cond in ("ONE", "TWO") for mode in ("RF", "RO")]

    diag = [{"condition": "C0", "layer": layer}, bridged("ONE", g), bridged("CF", g)]

    ext_layers = [{"condition": "C0", "layer": layer}]
    for lay, g_l in sorted(fz["per_layer_gain"].items(), key=lambda kv: int(kv[0])):
        if g_l is not None:  # layers unusable in Pilot A are not re-selected
            ext_layers += [bridged(cond, g_l, int(lay)) for cond in ("ONE", "TWO")]

    ext_masks = [{"condition": "C0", "layer": layer}, bridged("ONE", g)]
    for k in MASK_KS:
        ext_masks += [bridged("MASK", g, k=k, energy_mode="fixed", mask_direction="one"),
                      bridged("MASK", g, k=k, energy_mode="fixed", mask_direction="two"),
                      bridged("MASK", g, k=k, energy_mode="matched", mask_direction="one")]

    def stage(name: str, arms: list[dict], n: int, *, rotations_first: int = 0, qids=None, post=()) -> dict:
        layers = sorted({a["layer"] for a in arms if a["condition"] not in ("C0", "LANG_TAG", "LANG_UNTAG")})
        cfg = {"stage": name, "tag": "v1", "split": "main", "n_episodes": n, "seed": 0, "arms": arms,
               "all_rotations_first": rotations_first, "episodes_per_batch": 40, "max_rows": 256,
               "calibration": {lay: calibration[str(lay)]["path"] for lay in layers},
               "post": list(post), "frozen": fz}
        if qids is not None:
            cfg["qids"] = list(qids)
        return cfg

    return {
        "main": stage("main", main, fz["N"], rotations_first=DIAG_EPISODES, post=["confirmatory"]),
        "main_diag": stage("main_diag", diag, DIAG_EPISODES, rotations_first=DIAG_EPISODES,
                           qids=("ACC_RULE", "ACC_WORD", "CAP0", "CAP1"), post=["pilot_c"]),
        "ext_layers": stage("ext_layers", ext_layers, fz["N_ext"]),
        "ext_masks": stage("ext_masks", ext_masks, fz["N_ext"]),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("pilot_a_run", type=Path)
    ap.add_argument("pilot_b_run", type=Path)
    ap.add_argument("pilot_c_run", type=Path)
    ap.add_argument("--out-dir", type=Path, default=Path(__file__).resolve().parents[1] / "configs")
    args = ap.parse_args()
    configs = build_all(args.pilot_a_run, args.pilot_b_run, args.pilot_c_run)
    for name, cfg in configs.items():
        path = args.out_dir / f"{name}.yaml"
        header = HEADER.format(stage=name, a=args.pilot_a_run.name, b=args.pilot_b_run.name, c=args.pilot_c_run.name)
        path.write_text(header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=None, width=120))
        print(f"wrote {path}: {len(cfg['arms'])} arms x {cfg['n_episodes']} episodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
