"""Write the protocol-v3 B′ signal-pilot config from the S-B′ live-loop selection (PROTOCOL_V3 §2).

    python scripts/make_v3_bprime_signal.py S_LIVE_RUN [--out configs/v3/sig_bprime.yaml]

S_LIVE_RUN is a local copy of the S-B′ run directory. For every family with a selected point the
pilot runs the loop arm one-way and two-way, and the two-way no-loop control: KV-P at the family's
prefill weight (w_P for KV-PC, w for KV-ALL), which reads the same fixed memory without the partner's
live state. Both two-way arms are also asked with the connection cut (RF). The first comparison of
each study (loop minus no-loop in one_wins excess on START, FULL) decides go/no-go.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from mb.conditions import ArmConfig

ROOT = Path(__file__).resolve().parents[1]
QIDS = ["NOW", "NOW_R", "START", "START_R", "ACC_RULE", "ACC_WORD", "CAP0", "CAP1"]
N_SIGNAL = 80
BOTH = ["A", "B"]


def selection(run_dir: Path) -> dict[str, dict]:
    doc = json.loads((run_dir / "live_selection.json").read_text())
    if not doc.get("consumable"):
        raise SystemExit(f"{run_dir.name}: live selection is not consumable (smoke or incomplete)")
    chosen = {fam: sel for fam, sel in doc["selection"].items() if sel}
    if not chosen:
        raise SystemExit(f"{run_dir.name}: no family has a TWO point that passes the gates on both sides")
    return chosen


def family_arms(family: str, sel: dict) -> dict[str, dict]:
    """Arm specs by role for one family, keyed loop_one / loop_two / loop_rf / flat_two / flat_rf."""
    loop = {"interface": "kv", "kv_scope": family, "gain": float(sel["gain"]), "recipients": list(BOTH)}
    if family == "PC":
        loop["kv_w_live"] = float(sel["kv_w_live"])
    flat = {"interface": "kv", "kv_scope": "P", "gain": float(sel["gain"]), "recipients": list(BOTH)}
    specs = {"loop_one": {"condition": "ONE", **loop}, "loop_two": {"condition": "TWO", **loop},
             "loop_rf": {"condition": "TWO", **loop, "readout_mode": "RF"},
             "flat_two": {"condition": "TWO", **flat}, "flat_rf": {"condition": "TWO", **flat, "readout_mode": "RF"}}
    return {role: {**s, "recipients": list(s["recipients"])} for role, s in specs.items()}  # no YAML aliases


def name(spec: dict) -> str:
    return ArmConfig(**{**spec, "recipients": tuple(spec["recipients"])}).name


def build(chosen: dict[str, dict]) -> tuple[dict, list[str]]:
    arms, studies, descriptive, notes = [{"condition": "C0", "recipients": list(BOTH)}], {}, {}, []
    for family, sel in chosen.items():
        spec = family_arms(family, sel)
        n = {role: name(s) for role, s in spec.items()}
        arms += [s for s in spec.values() if name(s) not in {name(a) for a in arms}]
        studies[f"B'-{family}"] = [[n["loop_two"], n["flat_two"], "START", "one_wins_excess", "+"],
                                   [n["loop_rf"], n["flat_rf"], "START", "one_wins_excess", "+"],
                                   [n["loop_two"], n["flat_two"], "NOW", "one_wins_excess", "+"]]
        descriptive[f"B'-{family}"] = [[n["loop_two"], None, "START", "one_wins_excess", "0"],
                                       [n["flat_two"], None, "START", "one_wins_excess", "0"],
                                       [n["loop_two"], n["flat_two"], "START", "one_wins", "0"],
                                       [n["loop_two"], n["loop_one"], "START", "one_wins", "0"],
                                       [n["loop_rf"], n["loop_two"], "START", "one_wins", "0"],
                                       [n["loop_two"], n["flat_two"], "START", "swap", "0"],
                                       [n["loop_two"], n["flat_two"], "START", "both_third", "0"]]
        notes.append(f"{family}: selected {sel['arm']} (A-side ACC-rule {sel.get('acc_increment')}, "
                     f"CAP drop A {sel.get('cap_drop')} / B {sel.get('cap_drop_B')}); no-loop control {n['flat_two']}")
    cfg = {"stage": "v3_sig_bprime", "tag": "signal", "split": "v3_sig_bprime", "n_episodes": N_SIGNAL, "seed": 0,
           "arms": arms, "qids": QIDS, "episodes_per_batch": 40, "max_rows": 256, "post": ["pair_signal"],
           "params": {"studies": studies, "descriptive": descriptive, "min_effect": 0.10}}
    return cfg, notes


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("s_live", type=Path)
    ap.add_argument("--out", type=Path, default=ROOT / "configs" / "v3" / "sig_bprime.yaml")
    args = ap.parse_args()
    cfg, notes = build(selection(args.s_live))
    header = [f"# Protocol v3 B' signal pilot, generated by scripts/make_v3_bprime_signal.py from {args.s_live.name}."]
    header += [f"# {line}" for line in notes]
    args.out.write_text("\n".join(header) + "\n" + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True))
    print(args.out.read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
