"""Write configs/pilot_b.yaml from a finished, consumable Pilot A selection (protocol §10).

    python scripts/make_pilot_b.py PILOT_A_RUN_DIR [--out configs/pilot_b.yaml]

The Pilot B arms are fixed by the protocol: C0 and LANG-tag, ONE and TWO on the 8-point gain
grid and STATIC on its 8-point grid, all at the selected message form and layer, 40 episodes,
full readouts. The calibration file used by Pilot A is pinned explicitly.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from mb import analyze

HEADER = """# Pilot B (protocol v0.5.2 §10). GENERATED by scripts/make_pilot_b.py; do not edit by hand.
# Source Pilot A run: {src}
# Pilot A selection: form={form} layer={layer} gain={gain} score={score:.3f} nat
"""


def build(sel_path: Path) -> tuple[dict, str]:
    sel = json.loads(sel_path.read_text())
    s = sel.get("selection")
    if not sel.get("consumable") or not isinstance(s, dict) or not s.get("ok"):
        raise SystemExit(f"{sel_path}: Pilot A selection is not a consumable, successful selection")
    run_dir = sel_path.parent
    identity = json.loads((run_dir / "identity.json").read_text())
    layer, form = int(s["layer"]), str(s["form"])
    cal = identity["calibration"].get(str(layer))
    if cal is None:
        raise SystemExit(f"Pilot A identity has no calibration for layer {layer}")
    arms = [{"condition": "C0", "layer": layer}, {"condition": "LANG_TAG", "layer": layer}]
    for cond in ("ONE", "TWO"):
        arms += [{"condition": cond, "form": form, "layer": layer, "gain": g} for g in analyze.PILOT_B_GRID]
    arms += [{"condition": "STATIC", "form": form, "layer": layer, "gain": g} for g in analyze.STATIC_GRID]
    cfg = {
        "stage": "pilot_b", "tag": "grid", "split": "pilot_b", "n_episodes": 40, "seed": 0,
        "arms": arms, "episodes_per_batch": 40, "max_rows": 256,
        "calibration": {layer: cal["path"]},
        "post": ["select_pilot_b", "sample_size"],
    }
    header = HEADER.format(src=run_dir.name, form=form, layer=layer, gain=s["gain"], score=s["score"])
    return cfg, header


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("pilot_a_run", type=Path)
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "configs" / "pilot_b.yaml")
    args = ap.parse_args()
    cfg, header = build(args.pilot_a_run / "pilot_a_selection.json")
    args.out.write_text(header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=None, width=120))
    print(f"wrote {args.out} ({len(cfg['arms'])} arms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
