"""Write the protocol-v3 T3b signal-pilot config from the S-T3b match (PROTOCOL_V3 §5).

    python scripts/make_v3_t3b_signal.py S_T3B_RUN [--out configs/v3/sig_t3b.yaml]

S_T3B_RUN is a local copy of the S-T3b run. The pilot compares the strict third-person frame at the
matched weight w* with the second-person frame at w1 (unsaturated), keeps both frames at w2 as the
saturated replication, and adds C0. The first comparison (3ps w* − 2p w1 on M) is read by the
equivalence rule of §5; the second (2p w1 − C0) sets its margin.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from mb.conditions import ArmConfig

ROOT = Path(__file__).resolve().parents[1]
QIDS = ["NOW", "NOW_R", "START", "START_R", "WORD", "WORD_R", "ACC_RULE", "ACC_WORD", "CAP0", "CAP1", "U_CLOSED"]


def match(run_dir: Path) -> dict:
    doc = json.loads((run_dir / "arm_match.json").read_text())
    if not doc.get("consumable"):
        raise SystemExit(f"{run_dir.name}: arm match is not consumable (smoke or incomplete)")
    if not doc.get("match"):
        raise SystemExit(f"{run_dir.name}: no eligible strict third-person arm to match")
    return doc["match"]


def kv(gain: float, frame: str = "second") -> dict:
    spec = {"condition": "ONE", "interface": "kv", "kv_scope": "P", "gain": float(gain)}
    return {**spec, "partner_frame": frame} if frame != "second" else spec


def name(spec: dict) -> str:
    return ArmConfig(**spec).name


def build(m: dict) -> dict:
    strict, second_w1 = kv(m["gain"], "third_strict"), kv(1.0)
    arms = [{"condition": "C0"}, second_w1, strict, kv(2.0), kv(2.0, "third_strict")]
    arms = [a for i, a in enumerate(arms) if name(a) not in {name(b) for b in arms[:i]}]
    studies = {"T3b": [[name(strict), name(second_w1), "M", "0"], [name(second_w1), "C0/FULL", "M", "+"]]}
    return {"stage": "v3_sig_t3b", "tag": "signal", "split": "v3_sig_t3b", "n_episodes": 80, "seed": 0, "arms": arms,
            "qids": QIDS, "episodes_per_batch": 40, "max_rows": 256, "post": ["signal"],
            "params": {"studies": studies, "min_effect": 0.3}}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("s_t3b", type=Path)
    ap.add_argument("--out", type=Path, default=ROOT / "configs" / "v3" / "sig_t3b.yaml")
    args = ap.parse_args()
    m = match(args.s_t3b)
    note = (f"# strict third-person arm matched to ONE/KV-P/w1/FULL in {args.s_t3b.name}: {m['arm']} "
            f"(ACC {m['arm_acc']:.2f} vs {m['target_acc']:.2f}, matched={m['matched']})")
    args.out.write_text("# Protocol v3 T3b signal pilot, generated by scripts/make_v3_t3b_signal.py.\n" + note + "\n"
                        + yaml.safe_dump(build(m), sort_keys=False))
    print(args.out.read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
